// src/CodeEditor.js
import React, { useState } from 'react';
import axios from 'axios';

const CodeEditor = () => {
  const [code, setCode] = useState('');
  const [language, setLanguage] = useState('python3');
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);

  const handleCodeChange = (e) => {
    setCode(e.target.value);
  };

  const handleLanguageChange = (e) => {
    setLanguage(e.target.value);
  };

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const response = await axios.post(
        'https://us-central1-your-project-id.cloudfunctions.net/executeCode', //URL generated by Firebase when you deploy code on firebase cloud
        {
          code,
          language,
        }
      );
      setOutput(response.data.output);
    } catch (error) {
      setOutput('Error executing code.');
      console.error('Error:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <h1>Code Executor</h1>
      <div>
        <select onChange={handleLanguageChange} value={language}>
          <option value="python3">Python</option>
          <option value="java">Java</option>
          <option value="cpp">C++</option>
        </select>
      </div>
      <textarea
        value={code}
        onChange={handleCodeChange}
        rows="10"
        cols="50"
        placeholder="Write your code here..."
      />
      <br />
      <button onClick={handleSubmit} disabled={loading}>
        {loading ? 'Running...' : 'Run Code'}
      </button>

      <h3>Output:</h3>
      <pre>{output}</pre>
    </div>
  );
};

export default CodeEditor;
